apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultimate-mahjong-connect
  namespace: ultimate-mahjong-connect
  labels:
    app: ultimate-mahjong-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ultimate-mahjong-connect
  template:
    metadata:
      labels:
        app: ultimate-mahjong-connect
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: ultimate-mahjong-connect
        image: ghcr.io/lucaslepouliquen/ultimate-mahjong-connect-back-end-image:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: database-storage
          mountPath: /app/data
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_RASPBERRY
          value: "true"
        - name: CorsEnvironment
          value: "raspberry"
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: ultimate-mahjong-connect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi