apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ultimate-mahjong-connect
  namespace: ultimate-mahjong-connect
spec:
    ingressClassName: traefik
    rules:
    - host: ultimate-mahjong-connect.local
      http:
        paths:
        - backend:
            service:
              name: ultimate-mahjong-connect
              port:
                number: 8080
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - ultimate-mahjong-connect.local
      secretName: ingress-local-tls