apiVersion: v1
kind: Service
metadata:
  labels:
    app: ultimate-mahjong-connect
  name: ultimate-mahjong-connect
  namespace: game-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ultimate-mahjong-connect
  type: NodePort