name: Ultimate-Mahjong-Connect-CD

on: 
  workflow_dispatch: 

env:
  DEPLOYMENT_NAME: ultimate-mahjong-connect-front
  K8S_NAMESPACE: default

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 

      - name: Deploy to Raspberry Pi
        run: 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-back-end-image:latest
            
      - name: Fetch Kubernetes Cluster Details
        run:
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-back-end-image:latest -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8S_NAMESPACE }}