name: Ultimate-Mahjong-Connect-Front-CD

on: 
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          password: ${{ secrets.RASPBERRY_PASSWORD }}
          port: 50022 
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-back-end-image:latest
            if docker ps -a | grep -q "mon-api"; then
              docker stop mon-api || true
              docker rm mon-api || true
            fi
            docker run -d -p 8080:8080 --restart unless-stopped --name mon-api ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-back-end-image:latest

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set Kubeconfig file
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          
      - name: Fetch Kubernetes Cluster Details
        run: |
          kubectl version --short
          echo "----------------------------------------"
          kubectl get nodes
